CREATE DATABASE IF NOT EXISTS METRICMIND_DB;
CREATE SCHEMA IF NOT EXISTS METRICMIND_DB.RAW;

CREATE SCHEMA IF NOT EXISTS METRICMIND_DB.STAGING;
SHOW SCHEMAS IN DATABASE METRICMIND_DB;
CREATE SCHEMA IF NOT EXISTS METRICMIND_DB.RAW;
SHOW SCHEMAS IN DATABASE METRICMIND_DB;
CREATE TABLE IF NOT EXISTS METRICMIND_DB.RAW.CORPORATE_SALES_RAW (
    ORDER_ID VARCHAR(20),
    ORDER_DATE DATE,
    REGION VARCHAR(50),
    COUNTRY VARCHAR(50),
    PRODUCT VARCHAR(100),
    CATEGORY VARCHAR(50),
    QUANTITY INTEGER,
    REVENUE NUMBER(12,2),
    COST NUMBER(12,2)
);
SHOW TABLES IN SCHEMA METRICMIND_DB.RAW;