SELECT
    REGION,
    CATEGORY,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(REVENUE) AS TOTAL_REVENUE,
    SUM(COST) AS TOTAL_COST,
    SUM(REVENUE - COST) AS TOTAL_PROFIT
FROM {{ ref('stg_corporate_sales') }}
GROUP BY
    REGION,
    CATEGORY